name: todo_list
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  table_calendar: ^2.3.3
  flutter_slidable: ^0.5.7
  sqflite: ^1.3.2+2
  intl: ^0.16.1
  shared_preferences: ^2.0.5
  provider: ^4.3.3
  rxdart: ^0.25.0
  percent_indicator: ^3.0.1
  flutter_local_notifications: ^5.0.0+1
  google_mobile_ads: ^0.12.1+1
  flutter_native_timezone: ^1.0.10
  share: ^2.0.4
  material_design_icons_flutter: ^4.0.5955
  lottie: ^1.0.0
  in_app_purchase: ^0.5.1+1
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6
  rate_my_app: ^1.1.0+1
  flutter_email_sender: ^5.0.2
  tutorial_coach_mark: ^1.0.3
  package_info: ^2.0.2
  system_settings: ^2.0.0
  android_power_manager: ^0.1.6
  date_count_down: ^1.0.2
  animated_text_kit: ^4.2.1
  badges: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/



